language: generic # don't install any environment

script: bash ./deploy_gh_pages.sh
env:
  global:
  - ENCRYPTION_LABEL: "c8cff68dffdc"
  - COMMIT_AUTHOR_EMAIL: "xxyzzzq@gmail.com"

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data