#!/usr/bin/env bash

mkdir -p third_party

function sync_third_party() {
    local name=$1
    local origin=$2
    local version=$3

    if [ ! -d third_party/$name ]; then
	git init third_party/$name
	cd third_party/$name && git remote add origin $origin
	cd ../..
    fi

    cd third_party/$name && git fetch --tags origin && git checkout $version && git clean -xdf
    cd ../..
}

if [ ! -d third_party/quex ]; then
    git init third_party/quex
    cd third_party/quex && git remote add origin https://github.com/xxyzzzq/quex.git
    cd ../..
fi

while read line; do
    sync_third_party $line
done < third_party/versions.txt
